// automatically generated by the FlatBuffers compiler, do not modify

package fluxx.schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class AnimatableString : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : AnimatableString {
        __init(_i, _bb)
        return this
    }
    val isAnimated : Boolean
        get() {
            val o = __offset(4)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val staticValue : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val staticValueAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(6, 1)
    fun staticValueInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    fun keyframes(j: Int) : fluxx.schema.StringKeyframe? = keyframes(fluxx.schema.StringKeyframe(), j)
    fun keyframes(obj: fluxx.schema.StringKeyframe, j: Int) : fluxx.schema.StringKeyframe? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val keyframesLength : Int
        get() {
            val o = __offset(8); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsAnimatableString(_bb: ByteBuffer): AnimatableString = getRootAsAnimatableString(_bb, AnimatableString())
        fun getRootAsAnimatableString(_bb: ByteBuffer, obj: AnimatableString): AnimatableString {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createAnimatableString(builder: FlatBufferBuilder, isAnimated: Boolean, staticValueOffset: Int, keyframesOffset: Int) : Int {
            builder.startTable(3)
            addKeyframes(builder, keyframesOffset)
            addStaticValue(builder, staticValueOffset)
            addIsAnimated(builder, isAnimated)
            return endAnimatableString(builder)
        }
        fun startAnimatableString(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addIsAnimated(builder: FlatBufferBuilder, isAnimated: Boolean) = builder.addBoolean(0, isAnimated, false)
        fun addStaticValue(builder: FlatBufferBuilder, staticValue: Int) = builder.addOffset(1, staticValue, 0)
        fun addKeyframes(builder: FlatBufferBuilder, keyframes: Int) = builder.addOffset(2, keyframes, 0)
        fun createKeyframesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startKeyframesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endAnimatableString(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
