// automatically generated by the FlatBuffers compiler, do not modify

package fluxx.schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class AnimatableProperty2D : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : AnimatableProperty2D {
        __init(_i, _bb)
        return this
    }
    val isAnimated : Boolean
        get() {
            val o = __offset(4)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val staticX : Float
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getFloat(o + bb_pos) else 0.0f
        }
    val staticY : Float
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getFloat(o + bb_pos) else 0.0f
        }
    fun keyframes(j: Int) : fluxx.schema.Keyframe2D? = keyframes(fluxx.schema.Keyframe2D(), j)
    fun keyframes(obj: fluxx.schema.Keyframe2D, j: Int) : fluxx.schema.Keyframe2D? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val keyframesLength : Int
        get() {
            val o = __offset(10); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsAnimatableProperty2D(_bb: ByteBuffer): AnimatableProperty2D = getRootAsAnimatableProperty2D(_bb, AnimatableProperty2D())
        fun getRootAsAnimatableProperty2D(_bb: ByteBuffer, obj: AnimatableProperty2D): AnimatableProperty2D {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createAnimatableProperty2D(builder: FlatBufferBuilder, isAnimated: Boolean, staticX: Float, staticY: Float, keyframesOffset: Int) : Int {
            builder.startTable(4)
            addKeyframes(builder, keyframesOffset)
            addStaticY(builder, staticY)
            addStaticX(builder, staticX)
            addIsAnimated(builder, isAnimated)
            return endAnimatableProperty2D(builder)
        }
        fun startAnimatableProperty2D(builder: FlatBufferBuilder) = builder.startTable(4)
        fun addIsAnimated(builder: FlatBufferBuilder, isAnimated: Boolean) = builder.addBoolean(0, isAnimated, false)
        fun addStaticX(builder: FlatBufferBuilder, staticX: Float) = builder.addFloat(1, staticX, 0.0)
        fun addStaticY(builder: FlatBufferBuilder, staticY: Float) = builder.addFloat(2, staticY, 0.0)
        fun addKeyframes(builder: FlatBufferBuilder, keyframes: Int) = builder.addOffset(3, keyframes, 0)
        fun createKeyframesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startKeyframesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endAnimatableProperty2D(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
