// automatically generated by the FlatBuffers compiler, do not modify

package fluxx.schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class AnimatableColour : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : AnimatableColour {
        __init(_i, _bb)
        return this
    }
    val isAnimated : Boolean
        get() {
            val o = __offset(4)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val staticValue : Int
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getInt(o + bb_pos) else -1
        }
    fun keyframes(j: Int) : fluxx.schema.ColourKeyframe? = keyframes(fluxx.schema.ColourKeyframe(), j)
    fun keyframes(obj: fluxx.schema.ColourKeyframe, j: Int) : fluxx.schema.ColourKeyframe? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val keyframesLength : Int
        get() {
            val o = __offset(8); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsAnimatableColour(_bb: ByteBuffer): AnimatableColour = getRootAsAnimatableColour(_bb, AnimatableColour())
        fun getRootAsAnimatableColour(_bb: ByteBuffer, obj: AnimatableColour): AnimatableColour {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createAnimatableColour(builder: FlatBufferBuilder, isAnimated: Boolean, staticValue: Int, keyframesOffset: Int) : Int {
            builder.startTable(3)
            addKeyframes(builder, keyframesOffset)
            addStaticValue(builder, staticValue)
            addIsAnimated(builder, isAnimated)
            return endAnimatableColour(builder)
        }
        fun startAnimatableColour(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addIsAnimated(builder: FlatBufferBuilder, isAnimated: Boolean) = builder.addBoolean(0, isAnimated, false)
        fun addStaticValue(builder: FlatBufferBuilder, staticValue: Int) = builder.addInt(1, staticValue, -1)
        fun addKeyframes(builder: FlatBufferBuilder, keyframes: Int) = builder.addOffset(2, keyframes, 0)
        fun createKeyframesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startKeyframesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endAnimatableColour(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
