// automatically generated by the FlatBuffers compiler, do not modify

package fluxx.schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class ColourKeyframe : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ColourKeyframe {
        __init(_i, _bb)
        return this
    }
    val timeUs : Long
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getLong(o + bb_pos) else 0L
        }
    val argb : Int
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getInt(o + bb_pos) else -1
        }
    val easing : Byte
        get() {
            val o = __offset(8)
            return if(o != 0) bb.get(o + bb_pos) else 1
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsColourKeyframe(_bb: ByteBuffer): ColourKeyframe = getRootAsColourKeyframe(_bb, ColourKeyframe())
        fun getRootAsColourKeyframe(_bb: ByteBuffer, obj: ColourKeyframe): ColourKeyframe {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createColourKeyframe(builder: FlatBufferBuilder, timeUs: Long, argb: Int, easing: Byte) : Int {
            builder.startTable(3)
            addTimeUs(builder, timeUs)
            addArgb(builder, argb)
            addEasing(builder, easing)
            return endColourKeyframe(builder)
        }
        fun startColourKeyframe(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addTimeUs(builder: FlatBufferBuilder, timeUs: Long) = builder.addLong(0, timeUs, 0L)
        fun addArgb(builder: FlatBufferBuilder, argb: Int) = builder.addInt(1, argb, -1)
        fun addEasing(builder: FlatBufferBuilder, easing: Byte) = builder.addByte(2, easing, 1)
        fun endColourKeyframe(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
