// automatically generated by the FlatBuffers compiler, do not modify

package fluxx.schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Composition : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Composition {
        __init(_i, _bb)
        return this
    }
    fun layers(j: Int) : fluxx.schema.Layer? = layers(fluxx.schema.Layer(), j)
    fun layers(obj: fluxx.schema.Layer, j: Int) : fluxx.schema.Layer? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val layersLength : Int
        get() {
            val o = __offset(4); return if (o != 0) __vector_len(o) else 0
        }
    val width : Int
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getInt(o + bb_pos) else 1080
        }
    val height : Int
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getInt(o + bb_pos) else 1920
        }
    val durationUs : Long
        get() {
            val o = __offset(10)
            return if(o != 0) bb.getLong(o + bb_pos) else -1L
        }
    val fpsNumerator : Int
        get() {
            val o = __offset(12)
            return if(o != 0) bb.getInt(o + bb_pos) else 30
        }
    val fpsDenominator : Int
        get() {
            val o = __offset(14)
            return if(o != 0) bb.getInt(o + bb_pos) else 1
        }
    fun markers(j: Int): Marker? {
        val o = __offset(16)
        return if (o != 0) Marker().__assign(__indirect(__vector(o) + j * 4), bb) else null
    }
    val markersLength: Int get() { val o = __offset(16); return if (o != 0) __vector_len(o) else 0 }
    val startTimecodeUs: Long get() { val o = __offset(18); return if (o != 0) bb.getLong(o + bb_pos) else 0L }
    companion object {
        fun addStartTimecodeUs(builder: FlatBufferBuilder, value: Long) = builder.addLong(7, value, 0L)
        fun addMarkers(builder: FlatBufferBuilder, markers: Int) = builder.addOffset(6, markers, 0)
        fun createMarkersVector(builder: FlatBufferBuilder, data: IntArray): Int {
            builder.startVector(4, data.size, 4)
            for (i in data.lastIndex downTo 0) builder.addOffset(data[i])
            return builder.endVector()
        }
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsComposition(_bb: ByteBuffer): Composition = getRootAsComposition(_bb, Composition())
        fun getRootAsComposition(_bb: ByteBuffer, obj: Composition): Composition {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createComposition(builder: FlatBufferBuilder, layersOffset: Int, width: Int, height: Int, durationUs: Long, fpsNumerator: Int, fpsDenominator: Int, markersOffset: Int = 0, startTimecodeUs: Long = 0) : Int {
            builder.startTable(8)
            addStartTimecodeUs(builder, startTimecodeUs)
            addMarkers(builder, markersOffset)
            addDurationUs(builder, durationUs)
            addFpsDenominator(builder, fpsDenominator)
            addFpsNumerator(builder, fpsNumerator)
            addHeight(builder, height)
            addWidth(builder, width)
            addLayers(builder, layersOffset)
            return endComposition(builder)
        }
        fun startComposition(builder: FlatBufferBuilder) = builder.startTable(8)
        fun addLayers(builder: FlatBufferBuilder, layers: Int) = builder.addOffset(0, layers, 0)
        fun createLayersVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startLayersVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addWidth(builder: FlatBufferBuilder, width: Int) = builder.addInt(1, width, 1080)
        fun addHeight(builder: FlatBufferBuilder, height: Int) = builder.addInt(2, height, 1920)
        fun addDurationUs(builder: FlatBufferBuilder, durationUs: Long) = builder.addLong(3, durationUs, -1L)
        fun addFpsNumerator(builder: FlatBufferBuilder, fpsNumerator: Int) = builder.addInt(4, fpsNumerator, 30)
        fun addFpsDenominator(builder: FlatBufferBuilder, fpsDenominator: Int) = builder.addInt(5, fpsDenominator, 1)
        fun endComposition(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
