// automatically generated by the FlatBuffers compiler, do not modify

package fluxx.schema

@Suppress("unused")
class EasingType private constructor() {
    companion object {
        const val LINEAR: Byte = 0
        const val EASY_EASE: Byte = 1
    }
}
