// automatically generated by the FlatBuffers compiler, do not modify

package fluxx.schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Keyframe1D : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Keyframe1D {
        __init(_i, _bb)
        return this
    }
    val timeUs : Long
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getLong(o + bb_pos) else 0L
        }
    val value : Float
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getFloat(o + bb_pos) else 0.0f
        }
    val easing : Byte
        get() {
            val o = __offset(8)
            return if(o != 0) bb.get(o + bb_pos) else 1
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsKeyframe1D(_bb: ByteBuffer): Keyframe1D = getRootAsKeyframe1D(_bb, Keyframe1D())
        fun getRootAsKeyframe1D(_bb: ByteBuffer, obj: Keyframe1D): Keyframe1D {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createKeyframe1D(builder: FlatBufferBuilder, timeUs: Long, value: Float, easing: Byte) : Int {
            builder.startTable(3)
            addTimeUs(builder, timeUs)
            addValue(builder, value)
            addEasing(builder, easing)
            return endKeyframe1D(builder)
        }
        fun startKeyframe1D(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addTimeUs(builder: FlatBufferBuilder, timeUs: Long) = builder.addLong(0, timeUs, 0L)
        fun addValue(builder: FlatBufferBuilder, value: Float) = builder.addFloat(1, value, 0.0)
        fun addEasing(builder: FlatBufferBuilder, easing: Byte) = builder.addByte(2, easing, 1)
        fun endKeyframe1D(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
