// automatically generated by the FlatBuffers compiler, do not modify

package fluxx.schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Keyframe2D : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Keyframe2D {
        __init(_i, _bb)
        return this
    }
    val timeUs : Long
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getLong(o + bb_pos) else 0L
        }
    val x : Float
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getFloat(o + bb_pos) else 0.0f
        }
    val y : Float
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getFloat(o + bb_pos) else 0.0f
        }
    val easing : Byte
        get() {
            val o = __offset(10)
            return if(o != 0) bb.get(o + bb_pos) else 1
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsKeyframe2D(_bb: ByteBuffer): Keyframe2D = getRootAsKeyframe2D(_bb, Keyframe2D())
        fun getRootAsKeyframe2D(_bb: ByteBuffer, obj: Keyframe2D): Keyframe2D {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createKeyframe2D(builder: FlatBufferBuilder, timeUs: Long, x: Float, y: Float, easing: Byte) : Int {
            builder.startTable(4)
            addTimeUs(builder, timeUs)
            addY(builder, y)
            addX(builder, x)
            addEasing(builder, easing)
            return endKeyframe2D(builder)
        }
        fun startKeyframe2D(builder: FlatBufferBuilder) = builder.startTable(4)
        fun addTimeUs(builder: FlatBufferBuilder, timeUs: Long) = builder.addLong(0, timeUs, 0L)
        fun addX(builder: FlatBufferBuilder, x: Float) = builder.addFloat(1, x, 0.0)
        fun addY(builder: FlatBufferBuilder, y: Float) = builder.addFloat(2, y, 0.0)
        fun addEasing(builder: FlatBufferBuilder, easing: Byte) = builder.addByte(3, easing, 1)
        fun endKeyframe2D(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
