// automatically generated by the FlatBuffers compiler, do not modify

package fluxx.schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Layer : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Layer {
        __init(_i, _bb)
        return this
    }
    val id : ULong
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val positionX : Float
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getFloat(o + bb_pos) else 0.0f
        }
    val positionY : Float
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getFloat(o + bb_pos) else 0.0f
        }
    val scaleX : Float
        get() {
            val o = __offset(10)
            return if(o != 0) bb.getFloat(o + bb_pos) else 1.0f
        }
    val scaleY : Float
        get() {
            val o = __offset(12)
            return if(o != 0) bb.getFloat(o + bb_pos) else 1.0f
        }
    val rotation : Float
        get() {
            val o = __offset(14)
            return if(o != 0) bb.getFloat(o + bb_pos) else 0.0f
        }
    val opacity : Float
        get() {
            val o = __offset(16)
            return if(o != 0) bb.getFloat(o + bb_pos) else 1.0f
        }
    val assetUri : String?
        get() {
            val o = __offset(18)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val assetUriAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(18, 1)
    fun assetUriInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 18, 1)
    val type : Int
        get() {
            val o = __offset(20)
            return if(o != 0) bb.getInt(o + bb_pos) else 0
        }
    val zOrder : Int
        get() {
            val o = __offset(22)
            return if(o != 0) bb.getInt(o + bb_pos) else 0
        }
    val startUs : Long
        get() {
            val o = __offset(24)
            return if(o != 0) bb.getLong(o + bb_pos) else 0L
        }
    val sourceInUs : Long
        get() {
            val o = __offset(26)
            return if(o != 0) bb.getLong(o + bb_pos) else 0L
        }
    val durationUs : Long
        get() {
            val o = __offset(28)
            return if(o != 0) bb.getLong(o + bb_pos) else -1L
        }
    val visible : Boolean
        get() {
            val o = __offset(30)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else true
        }
    val assetId : String?
        get() {
            val o = __offset(32)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val assetIdAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(32, 1)
    fun assetIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 32, 1)
    val sourceDurationUs : Long
        get() {
            val o = __offset(34)
            return if(o != 0) bb.getLong(o + bb_pos) else -1L
        }
    val muted : Boolean
        get() {
            val o = __offset(36)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val audioGain : Float
        get() {
            val o = __offset(38)
            return if(o != 0) bb.getFloat(o + bb_pos) else 1.0f
        }
    val name : String?
        get() {
            val o = __offset(40)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val nameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(40, 1)
    fun nameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 40, 1)
    val solidColorArgb : Int
        get() {
            val o = __offset(42)
            return if(o != 0) bb.getInt(o + bb_pos) else -12290100
        }
    val referenceWidth : Int
        get() {
            val o = __offset(44)
            return if(o != 0) bb.getInt(o + bb_pos) else 0
        }
    val referenceHeight : Int
        get() {
            val o = __offset(46)
            return if(o != 0) bb.getInt(o + bb_pos) else 0
        }
    val animPosition : fluxx.schema.AnimatableProperty2D? get() = animPosition(fluxx.schema.AnimatableProperty2D())
    fun animPosition(obj: fluxx.schema.AnimatableProperty2D) : fluxx.schema.AnimatableProperty2D? {
        val o = __offset(48)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val animScale : fluxx.schema.AnimatableProperty2D? get() = animScale(fluxx.schema.AnimatableProperty2D())
    fun animScale(obj: fluxx.schema.AnimatableProperty2D) : fluxx.schema.AnimatableProperty2D? {
        val o = __offset(50)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val animRotation : fluxx.schema.AnimatableProperty1D? get() = animRotation(fluxx.schema.AnimatableProperty1D())
    fun animRotation(obj: fluxx.schema.AnimatableProperty1D) : fluxx.schema.AnimatableProperty1D? {
        val o = __offset(52)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val animOpacity : fluxx.schema.AnimatableProperty1D? get() = animOpacity(fluxx.schema.AnimatableProperty1D())
    fun animOpacity(obj: fluxx.schema.AnimatableProperty1D) : fluxx.schema.AnimatableProperty1D? {
        val o = __offset(54)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val keyframeAnchorUs : Long
        get() {
            val o = __offset(56)
            return if(o != 0) bb.getLong(o + bb_pos) else -1L
        }
    val hasKeyframeAnchor : Boolean
        get() {
            val o = __offset(58)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val anchorX : Float
        get() {
            val o = __offset(60)
            return if(o != 0) bb.getFloat(o + bb_pos) else 0.5f
        }
    val anchorY : Float
        get() {
            val o = __offset(62)
            return if(o != 0) bb.getFloat(o + bb_pos) else 0.5f
        }
    fun markers(j: Int) : fluxx.schema.Marker? = markers(fluxx.schema.Marker(), j)
    fun markers(obj: fluxx.schema.Marker, j: Int) : fluxx.schema.Marker? {
        val o = __offset(64)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val markersLength : Int
        get() {
            val o = __offset(64); return if (o != 0) __vector_len(o) else 0
        }
    val textPayload : fluxx.schema.TextPayload? get() = textPayload(fluxx.schema.TextPayload())
    fun textPayload(obj: fluxx.schema.TextPayload) : fluxx.schema.TextPayload? {
        val o = __offset(66)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsLayer(_bb: ByteBuffer): Layer = getRootAsLayer(_bb, Layer())
        fun getRootAsLayer(_bb: ByteBuffer, obj: Layer): Layer {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createLayer(builder: FlatBufferBuilder, id: ULong, positionX: Float, positionY: Float, scaleX: Float, scaleY: Float, rotation: Float, opacity: Float, assetUriOffset: Int, type: Int, zOrder: Int, startUs: Long, sourceInUs: Long, durationUs: Long, visible: Boolean, assetIdOffset: Int, sourceDurationUs: Long, muted: Boolean, audioGain: Float, nameOffset: Int, solidColorArgb: Int, referenceWidth: Int, referenceHeight: Int, animPositionOffset: Int, animScaleOffset: Int, animRotationOffset: Int, animOpacityOffset: Int, keyframeAnchorUs: Long, hasKeyframeAnchor: Boolean, anchorX: Float, anchorY: Float, markersOffset: Int, textPayloadOffset: Int) : Int {
            builder.startTable(32)
            addKeyframeAnchorUs(builder, keyframeAnchorUs)
            addSourceDurationUs(builder, sourceDurationUs)
            addDurationUs(builder, durationUs)
            addSourceInUs(builder, sourceInUs)
            addStartUs(builder, startUs)
            addId(builder, id)
            addTextPayload(builder, textPayloadOffset)
            addMarkers(builder, markersOffset)
            addAnchorY(builder, anchorY)
            addAnchorX(builder, anchorX)
            addAnimOpacity(builder, animOpacityOffset)
            addAnimRotation(builder, animRotationOffset)
            addAnimScale(builder, animScaleOffset)
            addAnimPosition(builder, animPositionOffset)
            addReferenceHeight(builder, referenceHeight)
            addReferenceWidth(builder, referenceWidth)
            addSolidColorArgb(builder, solidColorArgb)
            addName(builder, nameOffset)
            addAudioGain(builder, audioGain)
            addAssetId(builder, assetIdOffset)
            addZOrder(builder, zOrder)
            addType(builder, type)
            addAssetUri(builder, assetUriOffset)
            addOpacity(builder, opacity)
            addRotation(builder, rotation)
            addScaleY(builder, scaleY)
            addScaleX(builder, scaleX)
            addPositionY(builder, positionY)
            addPositionX(builder, positionX)
            addHasKeyframeAnchor(builder, hasKeyframeAnchor)
            addMuted(builder, muted)
            addVisible(builder, visible)
            return endLayer(builder)
        }
        fun startLayer(builder: FlatBufferBuilder) = builder.startTable(32)
        fun addId(builder: FlatBufferBuilder, id: ULong) = builder.addLong(0, id.toLong(), 0)
        fun addPositionX(builder: FlatBufferBuilder, positionX: Float) = builder.addFloat(1, positionX, 0.0)
        fun addPositionY(builder: FlatBufferBuilder, positionY: Float) = builder.addFloat(2, positionY, 0.0)
        fun addScaleX(builder: FlatBufferBuilder, scaleX: Float) = builder.addFloat(3, scaleX, 1.0)
        fun addScaleY(builder: FlatBufferBuilder, scaleY: Float) = builder.addFloat(4, scaleY, 1.0)
        fun addRotation(builder: FlatBufferBuilder, rotation: Float) = builder.addFloat(5, rotation, 0.0)
        fun addOpacity(builder: FlatBufferBuilder, opacity: Float) = builder.addFloat(6, opacity, 1.0)
        fun addAssetUri(builder: FlatBufferBuilder, assetUri: Int) = builder.addOffset(7, assetUri, 0)
        fun addType(builder: FlatBufferBuilder, type: Int) = builder.addInt(8, type, 0)
        fun addZOrder(builder: FlatBufferBuilder, zOrder: Int) = builder.addInt(9, zOrder, 0)
        fun addStartUs(builder: FlatBufferBuilder, startUs: Long) = builder.addLong(10, startUs, 0L)
        fun addSourceInUs(builder: FlatBufferBuilder, sourceInUs: Long) = builder.addLong(11, sourceInUs, 0L)
        fun addDurationUs(builder: FlatBufferBuilder, durationUs: Long) = builder.addLong(12, durationUs, -1L)
        fun addVisible(builder: FlatBufferBuilder, visible: Boolean) = builder.addBoolean(13, visible, true)
        fun addAssetId(builder: FlatBufferBuilder, assetId: Int) = builder.addOffset(14, assetId, 0)
        fun addSourceDurationUs(builder: FlatBufferBuilder, sourceDurationUs: Long) = builder.addLong(15, sourceDurationUs, -1L)
        fun addMuted(builder: FlatBufferBuilder, muted: Boolean) = builder.addBoolean(16, muted, false)
        fun addAudioGain(builder: FlatBufferBuilder, audioGain: Float) = builder.addFloat(17, audioGain, 1.0)
        fun addName(builder: FlatBufferBuilder, name: Int) = builder.addOffset(18, name, 0)
        fun addSolidColorArgb(builder: FlatBufferBuilder, solidColorArgb: Int) = builder.addInt(19, solidColorArgb, -12290100)
        fun addReferenceWidth(builder: FlatBufferBuilder, referenceWidth: Int) = builder.addInt(20, referenceWidth, 0)
        fun addReferenceHeight(builder: FlatBufferBuilder, referenceHeight: Int) = builder.addInt(21, referenceHeight, 0)
        fun addAnimPosition(builder: FlatBufferBuilder, animPosition: Int) = builder.addOffset(22, animPosition, 0)
        fun addAnimScale(builder: FlatBufferBuilder, animScale: Int) = builder.addOffset(23, animScale, 0)
        fun addAnimRotation(builder: FlatBufferBuilder, animRotation: Int) = builder.addOffset(24, animRotation, 0)
        fun addAnimOpacity(builder: FlatBufferBuilder, animOpacity: Int) = builder.addOffset(25, animOpacity, 0)
        fun addKeyframeAnchorUs(builder: FlatBufferBuilder, keyframeAnchorUs: Long) = builder.addLong(26, keyframeAnchorUs, -1L)
        fun addHasKeyframeAnchor(builder: FlatBufferBuilder, hasKeyframeAnchor: Boolean) = builder.addBoolean(27, hasKeyframeAnchor, false)
        fun addAnchorX(builder: FlatBufferBuilder, anchorX: Float) = builder.addFloat(28, anchorX, 0.5)
        fun addAnchorY(builder: FlatBufferBuilder, anchorY: Float) = builder.addFloat(29, anchorY, 0.5)
        fun addMarkers(builder: FlatBufferBuilder, markers: Int) = builder.addOffset(30, markers, 0)
        fun createMarkersVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startMarkersVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addTextPayload(builder: FlatBufferBuilder, textPayload: Int) = builder.addOffset(31, textPayload, 0)
        fun endLayer(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
