// automatically generated by the FlatBuffers compiler, do not modify

package fluxx.schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Marker : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Marker {
        __init(_i, _bb)
        return this
    }
    val id : ULong
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val timeUs : Long
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getLong(o + bb_pos) else 0L
        }
    val colorArgb : Int
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getInt(o + bb_pos) else -26624
        }
    val description : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val descriptionAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun descriptionInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsMarker(_bb: ByteBuffer): Marker = getRootAsMarker(_bb, Marker())
        fun getRootAsMarker(_bb: ByteBuffer, obj: Marker): Marker {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createMarker(builder: FlatBufferBuilder, id: ULong, timeUs: Long, colorArgb: Int, descriptionOffset: Int) : Int {
            builder.startTable(4)
            addTimeUs(builder, timeUs)
            addId(builder, id)
            addDescription(builder, descriptionOffset)
            addColorArgb(builder, colorArgb)
            return endMarker(builder)
        }
        fun startMarker(builder: FlatBufferBuilder) = builder.startTable(4)
        fun addId(builder: FlatBufferBuilder, id: ULong) = builder.addLong(0, id.toLong(), 0)
        fun addTimeUs(builder: FlatBufferBuilder, timeUs: Long) = builder.addLong(1, timeUs, 0L)
        fun addColorArgb(builder: FlatBufferBuilder, colorArgb: Int) = builder.addInt(2, colorArgb, -26624)
        fun addDescription(builder: FlatBufferBuilder, description: Int) = builder.addOffset(3, description, 0)
        fun endMarker(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
