// automatically generated by the FlatBuffers compiler, do not modify

package fluxx.schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Project : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Project {
        __init(_i, _bb)
        return this
    }
    val version : Int
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getInt(o + bb_pos) else 0
        }
    val mainComp : fluxx.schema.Composition? get() = mainComp(fluxx.schema.Composition())
    fun mainComp(obj: fluxx.schema.Composition) : fluxx.schema.Composition? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsProject(_bb: ByteBuffer): Project = getRootAsProject(_bb, Project())
        fun getRootAsProject(_bb: ByteBuffer, obj: Project): Project {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createProject(builder: FlatBufferBuilder, version: Int, mainCompOffset: Int) : Int {
            builder.startTable(2)
            addMainComp(builder, mainCompOffset)
            addVersion(builder, version)
            return endProject(builder)
        }
        fun startProject(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addVersion(builder: FlatBufferBuilder, version: Int) = builder.addInt(0, version, 0)
        fun addMainComp(builder: FlatBufferBuilder, mainComp: Int) = builder.addOffset(1, mainComp, 0)
        fun endProject(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
        fun finishProjectBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finish(offset)
        fun finishSizePrefixedProjectBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finishSizePrefixed(offset)
    }
}
