// automatically generated by the FlatBuffers compiler, do not modify

package fluxx.schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class StringKeyframe : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : StringKeyframe {
        __init(_i, _bb)
        return this
    }
    val timeUs : Long
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getLong(o + bb_pos) else 0L
        }
    val value : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val valueAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(6, 1)
    fun valueInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsStringKeyframe(_bb: ByteBuffer): StringKeyframe = getRootAsStringKeyframe(_bb, StringKeyframe())
        fun getRootAsStringKeyframe(_bb: ByteBuffer, obj: StringKeyframe): StringKeyframe {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createStringKeyframe(builder: FlatBufferBuilder, timeUs: Long, valueOffset: Int) : Int {
            builder.startTable(2)
            addTimeUs(builder, timeUs)
            addValue(builder, valueOffset)
            return endStringKeyframe(builder)
        }
        fun startStringKeyframe(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addTimeUs(builder: FlatBufferBuilder, timeUs: Long) = builder.addLong(0, timeUs, 0L)
        fun addValue(builder: FlatBufferBuilder, value: Int) = builder.addOffset(1, value, 0)
        fun endStringKeyframe(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
