// automatically generated by the FlatBuffers compiler, do not modify

package fluxx.schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class TextPayload : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : TextPayload {
        __init(_i, _bb)
        return this
    }
    val source : fluxx.schema.AnimatableString? get() = source(fluxx.schema.AnimatableString())
    fun source(obj: fluxx.schema.AnimatableString) : fluxx.schema.AnimatableString? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val size : fluxx.schema.AnimatableProperty1D? get() = size(fluxx.schema.AnimatableProperty1D())
    fun size(obj: fluxx.schema.AnimatableProperty1D) : fluxx.schema.AnimatableProperty1D? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val fill : fluxx.schema.AnimatableColour? get() = fill(fluxx.schema.AnimatableColour())
    fun fill(obj: fluxx.schema.AnimatableColour) : fluxx.schema.AnimatableColour? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val fontId : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val fontIdAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun fontIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    val alignment : Int
        get() {
            val o = __offset(12)
            return if(o != 0) bb.getInt(o + bb_pos) else 1
        }
    fun textAnimators(j: Int) : fluxx.schema.TextAnimator? = textAnimators(fluxx.schema.TextAnimator(), j)
    fun textAnimators(obj: fluxx.schema.TextAnimator, j: Int) : fluxx.schema.TextAnimator? {
        val o = __offset(14)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val textAnimatorsLength : Int
        get() {
            val o = __offset(14); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsTextPayload(_bb: ByteBuffer): TextPayload = getRootAsTextPayload(_bb, TextPayload())
        fun getRootAsTextPayload(_bb: ByteBuffer, obj: TextPayload): TextPayload {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createTextPayload(builder: FlatBufferBuilder, sourceOffset: Int, sizeOffset: Int, fillOffset: Int, fontIdOffset: Int, alignment: Int, textAnimatorsOffset: Int) : Int {
            builder.startTable(6)
            addTextAnimators(builder, textAnimatorsOffset)
            addAlignment(builder, alignment)
            addFontId(builder, fontIdOffset)
            addFill(builder, fillOffset)
            addSize(builder, sizeOffset)
            addSource(builder, sourceOffset)
            return endTextPayload(builder)
        }
        fun startTextPayload(builder: FlatBufferBuilder) = builder.startTable(6)
        fun addSource(builder: FlatBufferBuilder, source: Int) = builder.addOffset(0, source, 0)
        fun addSize(builder: FlatBufferBuilder, size: Int) = builder.addOffset(1, size, 0)
        fun addFill(builder: FlatBufferBuilder, fill: Int) = builder.addOffset(2, fill, 0)
        fun addFontId(builder: FlatBufferBuilder, fontId: Int) = builder.addOffset(3, fontId, 0)
        fun addAlignment(builder: FlatBufferBuilder, alignment: Int) = builder.addInt(4, alignment, 1)
        fun addTextAnimators(builder: FlatBufferBuilder, textAnimators: Int) = builder.addOffset(5, textAnimators, 0)
        fun createTextAnimatorsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startTextAnimatorsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endTextPayload(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
