// automatically generated by the FlatBuffers compiler, do not modify

package fluxx.schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class TextAnimator : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : TextAnimator {
        __init(_i, _bb)
        return this
    }
    val version : UInt
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 1u
        }
    val rangeSelector : fluxx.schema.TextRangeSelector? get() = rangeSelector(fluxx.schema.TextRangeSelector())
    fun rangeSelector(obj: fluxx.schema.TextRangeSelector) : fluxx.schema.TextRangeSelector? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    fun propertyOverrides(j: Int) : fluxx.schema.TextPropertyOverride? = propertyOverrides(fluxx.schema.TextPropertyOverride(), j)
    fun propertyOverrides(obj: fluxx.schema.TextPropertyOverride, j: Int) : fluxx.schema.TextPropertyOverride? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val propertyOverridesLength : Int
        get() {
            val o = __offset(8); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsTextAnimator(_bb: ByteBuffer): TextAnimator = getRootAsTextAnimator(_bb, TextAnimator())
        fun getRootAsTextAnimator(_bb: ByteBuffer, obj: TextAnimator): TextAnimator {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createTextAnimator(builder: FlatBufferBuilder, version: UInt, rangeSelectorOffset: Int, propertyOverridesOffset: Int) : Int {
            builder.startTable(3)
            addPropertyOverrides(builder, propertyOverridesOffset)
            addRangeSelector(builder, rangeSelectorOffset)
            addVersion(builder, version)
            return endTextAnimator(builder)
        }
        fun startTextAnimator(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addVersion(builder: FlatBufferBuilder, version: UInt) = builder.addInt(0, version.toInt(), 1)
        fun addRangeSelector(builder: FlatBufferBuilder, rangeSelector: Int) = builder.addOffset(1, rangeSelector, 0)
        fun addPropertyOverrides(builder: FlatBufferBuilder, propertyOverrides: Int) = builder.addOffset(2, propertyOverrides, 0)
        fun createPropertyOverridesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startPropertyOverridesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endTextAnimator(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
