// automatically generated by the FlatBuffers compiler, do not modify

package fluxx.schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class TextRangeSelector : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : TextRangeSelector {
        __init(_i, _bb)
        return this
    }
    val version : UInt
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 1u
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsTextRangeSelector(_bb: ByteBuffer): TextRangeSelector = getRootAsTextRangeSelector(_bb, TextRangeSelector())
        fun getRootAsTextRangeSelector(_bb: ByteBuffer, obj: TextRangeSelector): TextRangeSelector {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createTextRangeSelector(builder: FlatBufferBuilder, version: UInt) : Int {
            builder.startTable(1)
            addVersion(builder, version)
            return endTextRangeSelector(builder)
        }
        fun startTextRangeSelector(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addVersion(builder: FlatBufferBuilder, version: UInt) = builder.addInt(0, version.toInt(), 1)
        fun endTextRangeSelector(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
