file(READ "${INPUT}/text.vert.spv" VERT HEX)
file(READ "${INPUT}/text.frag.spv" FRAG HEX)
set(CONTENT "#pragma once\n#include <cstdint>\n")
foreach(STAGE VERT FRAG)
    string(REGEX MATCHALL "........" WORDS "${${STAGE}}")
    string(APPEND CONTENT "inline constexpr uint32_t TEXT_${STAGE}[] = {\n")
    foreach(WORD IN LISTS WORDS)
        string(SUBSTRING "${WORD}" 0 2 A)
        string(SUBSTRING "${WORD}" 2 2 B)
        string(SUBSTRING "${WORD}" 4 2 C)
        string(SUBSTRING "${WORD}" 6 2 D)
        string(APPEND CONTENT "0x${D}${C}${B}${A},")
    endforeach()
    string(APPEND CONTENT "};\n")
endforeach()
file(WRITE "${OUTPUT}" "${CONTENT}")
